### ISSUE TITLE
search dashboards

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/DashboardService#12]
Use elastic search

* [x] Basic search `name`, `repo`, `theme` fields
* [x] If not authenticated search **public** dashboards only
* [x] if authenticated include my **private** dashboards

**Comment by brettminnie** [comment]
Rather don't

Dewey Decimal cards or nothing

On Thu, May 14, 2015 at 2:08 PM, Eddie Abou-Jaoude <notifications@github.com

**Comment by eddiejaoude** [comment]
> Dewey Decimal cards or nothing

 Huh?
